BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[Revenue] (
    [id] INT NOT NULL IDENTITY(1,1),
    [month] NVARCHAR(1000) NOT NULL,
    [revenue] FLOAT(53) NOT NULL,
    [createdAt] DATETIME2 NOT NULL CONSTRAINT [Revenue_createdAt_df] DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT [Revenue_pkey] PRIMARY KEY CLUSTERED ([id])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
